POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Why backend architecture matters",
  "author": "Full Stack Open Student",
  "url": "https://fullstackopen.com/en/part4",
  "likes": 7
}