### LOCAL POST #1 WITHOUT TOKEN
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Why backend architecture matters",
  "author": "Full Stack Open Student",
  "url": "https://fullstackopen.com/en/part4",
  "likes": 7
}

### LOCAL POST #2 WITH TOKEN
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphY2tmbG93IiwiaWQiOiI2YTI4MzZlYWVhYmVlZWUzNDJjYmFiYzIiLCJpYXQiOjE3ODEwMjA0Mjd9.DRNqS58mUcbmYudbCJWZ7SwVmYUrAEnhnkCcwCm_Bbs

{
  "title": "Express middleware explained",
  "author": "Node Developer",
  "url": "https://expressjs.com/en/guide/using-middleware.html",
  "likes": 21
}

### LOCAL POST #3 SECOND USER WITH TOKEN
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY29uZG9uZSIsImlkIjoiNmEyODUxY2VhM2ViOTVmYzllZWM4YTE1IiwiaWF0IjoxNzgxMDI3MzUwfQ.Iv6bvYegps4D3E0c7eG2t14DV_Wc3wDQhKhwTIt33-g

{
  "title": "Second users blog",
  "author": "Test Author",
  "url": "https://example.com/blogs",
  "likes": 21
}